Removed unnecessary null checking
CrazyKamenwik/Marsh pull request #17
Opened 2023-02-15 13:29 UTC by Finka95

- Removed unnecessary null checking by changing the entity search method in TicketService and UserService
- Replase AsNoTracking method in GenericRepository

2023-02-15 13:41 UTC, nantonov requested changes

2023-02-15 13:41 UTC, nantonov commented on TicketSystem/TicketSystem.BLL/Services/TicketService.cs
> +        await GetTicketByIdAsync(ticket.Id, cancellationToken);
Why GetTicketByIdAsync doesn't return the ticket? Looks strange

2023-02-15 13:41 UTC, nantonov commented on TicketSystem/TicketSystem.BLL/Services/TicketService.cs
> +        var ticket = await GetTicketByIdAsync(id, cancellationToken);
We can delete by id, without retrieving ticket

2023-02-16 12:56 UTC, nantonov requested changes

2023-02-16 12:56 UTC, nantonov commented on TicketSystem/TicketSystem.DAL/Repositories/GenericRepository.cs
> +        var item = await _dbSet.FirstAsync(x => x.Id == id, cancellationToken: cancellationToken);
FirstOrDefault will be better 
If we already don't have this resource - good news, we already done this job :)

2023-02-16 12:56 UTC, nantonov commented on TicketSystem/TicketSystem.DAL/Repositories/GenericRepository.cs
> +        return await entity.AsNoTracking().FirstAsync(t => t.Id == id, cancellationToken);
It's okay to return null

2023-02-16 12:56 UTC, nantonov commented on TicketSystem/TicketSystem/Middleware/ExceptionMiddleware.cs
> +using TicketSystem.DAL.Exceptions;
API cannot use DAL

2023-02-16 13:35 UTC, nantonov approved these changes

2023-02-16 13:40 UTC, 5Ka-me approved these changes

2023-02-16 13:40 UTC, moltenessence approved these changes

2023-02-16 13:40 UTC, merged

2023-02-16 13:41 UTC, Genresal approved these changes

2023-02-17 07:28 UTC, Genresal approved these changes